/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./../../components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./../../components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./../../components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./../../components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./../../components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./../../components/icons/IconTooling.vue')['default']
    MovingSprite: typeof import('./../../components/MovingSprite.vue')['default']
    MyStandardButton: typeof import('./../../components/MyStandardButton.vue')['default']
    PixiCanvas: typeof import('./../../components/PixiCanvas.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./../../components/TheWelcome.vue')['default']
    TopWindows: typeof import('./../../components/TopWindows.vue')['default']
    UpdatePopupWin: typeof import('./../../components/windows/UpdatePopupWin.vue')['default']
    WelcomeItem: typeof import('./../../components/WelcomeItem.vue')['default']
  }
}
