/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdvWin: typeof import('./../../components/windows/AdvWin.vue')['default']
    BonusRank: typeof import('./../../components/windows/BonusRank.vue')['default']
    BonusRule: typeof import('./../../components/windows/BonusRule.vue')['default']
    BonusWin: typeof import('./../../components/windows/BonusWin.vue')['default']
    FreePlayWin: typeof import('./../../components/windows/FreePlayWin.vue')['default']
    HelloWorld: typeof import('./../../components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./../../components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./../../components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./../../components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./../../components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./../../components/icons/IconTooling.vue')['default']
    InfoWin: typeof import('./../../components/windows/InfoWin.vue')['default']
    LoginWin: typeof import('./../../components/windows/LoginWin.vue')['default']
    MaintenenceWin: typeof import('./../../components/windows/MaintenenceWin.vue')['default']
    Message: typeof import('./../../components/windows/Message.vue')['default']
    MessageWin: typeof import('./../../components/windows/MessageWin.vue')['default']
    MovingSprite: typeof import('./../../components/MovingSprite.vue')['default']
    MyStandardButton: typeof import('./../../components/MyStandardButton.vue')['default']
    NewPassWin: typeof import('./../../components/windows/NewPassWin.vue')['default']
    NewsWin: typeof import('./../../components/windows/NewsWin.vue')['default']
    NewWebsite: typeof import('./../../components/windows/NewWebsite.vue')['default']
    NewWebsiteWin: typeof import('./../../components/windows/NewWebsiteWin.vue')['default']
    PixiCanvas: typeof import('./../../components/PixiCanvas.vue')['default']
    ReferFriend: typeof import('./../../components/windows/ReferFriend.vue')['default']
    RegWin: typeof import('./../../components/windows/RegWin.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignPhoneWin: typeof import('./../../components/windows/SignPhoneWin.vue')['default']
    TheWelcome: typeof import('./../../components/TheWelcome.vue')['default']
    TopWindows: typeof import('./../../components/TopWindows.vue')['default']
    UpdatePopupWin: typeof import('./../../components/windows/UpdatePopupWin.vue')['default']
    WelcomeItem: typeof import('./../../components/WelcomeItem.vue')['default']
  }
}
