/**
 * array game list
 */
export let Games: any = {
  slots: [
    {
      id: 5861,
      src: '/frontend/Default/ico/WickedCircusYGG.png',
      size: 'small',
      tag: 'hot',
      url: '/game/open/WickedCircusYGG?api_exit=/',
      orientation: 0,
    },
    {
      id: 5863,
      src: '/frontend/Default/ico/IncineratorYGG.png',
      size: 'small',
      tag: 'hot',
      url: '/game/open/IncineratorYGG?api_exit=/',
      orientation: 0,
    },
    {
      id: 5864,
      src: '/frontend/Default/ico/WildMantraYGG.png',
      size: 'small',
      tag: 'hot',
      url: '/game/open/WildMantraYGG?api_exit=/',
      orientation: 0,
    },
    {
      id: 5865,
      src: '/frontend/Default/ico/BeautyAndBeastYGG.png',
      size: 'small',
      tag: 'hot',
      url: '/game/open/BeautyAndBeastYGG?api_exit=/',
      orientation: 0,
    },
    {
      id: 5866,
      src: '/frontend/Default/ico/DarkJokeRizesYGG.png',
      size: 'small',
      tag: 'hot',
      url: '/game/open/DarkJokeRizesYGG?api_exit=/',
      orientation: 0,
    },
    {
      id: 5867,
      src: '/frontend/Default/ico/ZeusVSThorYGG.png',
      size: 'small',
      tag: 'hot',
      url: '/game/open/ZeusVSThorYGG?api_exit=/',
      orientation: 0,
    },
    {
      id: 5868,
      src: '/frontend/Default/ico/RainbowRyanYGG.png',
      size: 'small',
      tag: 'hot',
      url: '/game/open/RainbowRyanYGG?api_exit=/',
      orientation: 0,
    },
    {
      id: 5869,
      src: '/frontend/Default/ico/AvatarsGatewayGuardiansYGG.png',
      size: 'small',
      tag: 'hot',
      url: '/game/open/AvatarsGatewayGuardiansYGG?api_exit=/',
      orientation: 0,
    },
    {
      id: 5870,
      src: '/frontend/Default/ico/CleosHeartNG.png',
      size: 'small',
      tag: 'hot',
      url: '/game/open/CleosHeartNG?api_exit=/',
      orientation: 0,
    },
    {
      id: 5871,
      src: '/frontend/Default/ico/CloverStonesNG.png',
      size: 'small',
      tag: 'hot',
      url: '/game/open/CloverStonesNG?api_exit=/',
      orientation: 0,
    },
    {
      id: 5872,
      src: '/frontend/Default/ico/CrazyScientistNG.png',
      size: 'small',
      tag: 'hot',
      url: '/game/open/CrazyScientistNG?api_exit=/',
      orientation: 0,
    },
    {
      id: 5873,
      src: '/frontend/Default/ico/DragonSevensNG.png',
      size: 'small',
      tag: 'hot',
      url: '/game/open/DragonSevensNG?api_exit=/',
      orientation: 0,
    },
    {
      id: 5874,
      src: '/frontend/Default/ico/FortuneCashNG.png',
      size: 'small',
      tag: 'hot',
      url: '/game/open/FortuneCashNG?api_exit=/',
      orientation: 0,
    },
    {
      id: 5875,
      src: '/frontend/Default/ico/FruitCashNG.png',
      size: 'small',
      tag: 'hot',
      url: '/game/open/FruitCashNG?api_exit=/',
      orientation: 0,
    },
    {
      id: 5876,
      src: '/frontend/Default/ico/HitInVegasNG.png',
      size: 'small',
      tag: 'hot',
      url: '/game/open/HitInVegasNG?api_exit=/',
      orientation: 0,
    },
    {
      id: 5877,
      src: '/frontend/Default/ico/MagicDragonsNG.png',
      size: 'small',
      tag: 'hot',
      url: '/game/open/MagicDragonsNG?api_exit=/',
      orientation: 0,
    },
    {
      id: 5878,
      src: '/frontend/Default/ico/MagicTreeNG.png',
      size: 'small',
      tag: 'hot',
      url: '/game/open/MagicTreeNG?api_exit=/',
      orientation: 0,
    },
    {
      id: 5879,
      src: '/frontend/Default/ico/MMALegendsNG.png',
      size: 'small',
      tag: 'hot',
      url: '/game/open/MMALegendsNG?api_exit=/',
      orientation: 0,
    },
    {
      id: 5880,
      src: '/frontend/Default/ico/SpaceRocksNG.png',
      size: 'small',
      tag: 'hot',
      url: '/game/open/SpaceRocksNG?api_exit=/',
      orientation: 0,
    },
    {
      id: 5881,
      src: '/frontend/Default/ico/VolcanoFruitsNG.png',
      size: 'small',
      tag: 'hot',
      url: '/game/open/VolcanoFruitsNG?api_exit=/',
      orientation: 0,
    },
    {
      id: 5882,
      src: '/frontend/Default/ico/WildBuffaloNG.png',
      size: 'small',
      tag: 'hot',
      url: '/game/open/WildBuffaloNG?api_exit=/',
      orientation: 0,
    },
    {
      id: 5990,
      src: '/frontend/Default/ico/VikingsGoWildYGG.png',
      size: 'small',
      tag: 'hot',
      url: '/game/open/VikingsGoWildYGG?api_exit=/',
      orientation: 0,
    },
    {
      id: 5994,
      src: '/frontend/Default/ico/PenguinCityYGG.png',
      size: 'small',
      tag: 'hot',
      url: '/game/open/PenguinCityYGG?api_exit=/',
      orientation: 0,
    },
    {
      id: 6141,
      src: '/frontend/Default/ico/ValleyOfGodsYGG.png',
      size: 'small',
      tag: 'hot',
      url: '/game/open/ValleyOfGodsYGG?api_exit=/',
      orientation: 0,
    },
    {
      id: 6148,
      src: '/frontend/Default/ico/TrollsBridgeYGG.png',
      size: 'small',
      tag: 'hot',
      url: '/game/open/TrollsBridgeYGG?api_exit=/',
      orientation: 0,
    },
    {
      id: 6155,
      src: '/frontend/Default/ico/NirvanaYGG.png',
      size: 'small',
      tag: 'hot',
      url: '/game/open/NirvanaYGG?api_exit=/',
      orientation: 0,
    },
    {
      id: 6162,
      src: '/frontend/Default/ico/ChampionsofRomeYGG.png',
      size: 'small',
      tag: 'hot',
      url: '/game/open/ChampionsofRomeYGG?api_exit=/',
      orientation: 0,
    },
    {
      id: 6176,
      src: '/frontend/Default/ico/BloodMoonWildsYGG.png',
      size: 'small',
      tag: 'hot',
      url: '/game/open/BloodMoonWildsYGG?api_exit=/',
      orientation: 0,
    },
    {
      id: 6190,
      src: '/frontend/Default/ico/PumpkinSmashYGG.png',
      size: 'small',
      tag: 'hot',
      url: '/game/open/PumpkinSmashYGG?api_exit=/',
      orientation: 0,
    },
    {
      id: 6204,
      src: '/frontend/Default/ico/HadesGigabloxYGG.png',
      size: 'small',
      tag: 'hot',
      url: '/game/open/HadesGigabloxYGG?api_exit=/',
      orientation: 0,
    },
    {
      id: 6211,
      src: '/frontend/Default/ico/HanzosDojoYGG.png',
      size: 'small',
      tag: 'hot',
      url: '/game/open/HanzosDojoYGG?api_exit=/',
      orientation: 0,
    },
    {
      id: 6225,
      src: '/frontend/Default/ico/HanzosDojoYGG.png',
      size: 'small',
      tag: 'hot',
      url: '/game/open/HanzosDojoYGG?api_exit=/',
      orientation: 0,
    },
  ],
  fishes: [
    {
      id: 5859,
      src: '/frontend/Default/ico/MonsterFrenzyPGD.png',
      size: 'big',
      tag: 'new',
      url: '/game/open/MonsterFrenzyPGD?api_exit=/',
      orientation: 0,
    },
    {
      id: 5860,
      src: '/frontend/Default/ico/AladdinAdventurePGD.png',
      size: 'big',
      tag: 'cold',
      url: '/game/open/AladdinAdventurePGD?api_exit=/',
      orientation: 0,
    },
    {
      id: 5982,
      src: '/frontend/Default/ico/FishHunterGhostPGD.png',
      size: 'big',
      tag: 'hot',
      url: '/game/open/FishHunterGhostPGD?api_exit=/',
      orientation: 0,
    },
    {
      id: 5986,
      src: '/frontend/Default/ico/FishHunterKingKongPGD.png',
      size: 'big',
      tag: 'new',
      url: '/game/open/FishHunterKingKongPGD?api_exit=/',
      orientation: 0,
    },
    {
      id: 6232,
      src: '/frontend/Default/ico/FishHunterKingKongPGD.png',
      size: 'big',
      tag: 'new',
      url: '/game/open/FishHunterKingKongPGD?api_exit=/',
      orientation: 0,
    },
    {
      id: 6239,
      src: '/frontend/Default/ico/FishHunterKingKongPGD.png',
      size: 'big',
      tag: 'new',
      url: '/game/open/FishHunterKingKongPGD?api_exit=/',
      orientation: 0,
    },
    {
      id: 6293,
      src: '/frontend/Default/ico/FishHunterKingKongPGD.png',
      size: 'big',
      tag: 'new',
      url: '/game/open/FishHunterKingKongPGD?api_exit=/',
      orientation: 0,
    },
  ],
  firelinks: [
    {
      id: 5858,
      src: '/frontend/Default/ico/UltraBlazingFireLink.png',
      size: 'big',
      tag: 'hot',
      url: '/game/open/UltraBlazingFireLink?api_exit=/',
      orientation: 1,
    },
    {
      id: 6057,
      src: '/frontend/Default/ico/NorthShore.png',
      size: 'big',
      tag: 'hot',
      url: '/game/open/NorthShore?api_exit=/',
      orientation: 1,
    },
    {
      id: 6092,
      src: '/frontend/Default/ico/ByTheBay.png',
      size: 'big',
      tag: 'hot',
      url: '/game/open/ByTheBay?api_exit=/',
      orientation: 1,
    } /*,{"id":6099,"src":"\/frontend\/Default\/ico\/ChinaStreet.png","size":"big","tag":"hot","url":"\/game\/open\/ChinaStreet?api_exit=\/","orientation":1},{"id":6106,"src":"\/frontend\/Default\/ico\/GlacierGold.png","size":"big","tag":"hot","url":"\/game\/open\/GlacierGold?api_exit=\/","orientation":1},{"id":6113,"src":"\/frontend\/Default\/ico\/OlveraStreet.png","size":"big","tag":"hot","url":"\/game\/open\/OlveraStreet?api_exit=\/","orientation":1},{"id":6120,"src":"\/frontend\/Default\/ico\/RiverWalk.png","size":"big","tag":"hot","url":"\/game\/open\/RiverWalk?api_exit=\/","orientation":1},{"id":6127,"src":"\/frontend\/Default\/ico\/Route66.png","size":"big","tag":"hot","url":"\/game\/open\/Route66?api_exit=\/","orientation":1},{"id":6134,"src":"\/frontend\/Default\/ico\/RueRoyale.png","size":"big","tag":"hot","url":"\/game\/open\/RueRoyale?api_exit=\/","orientation":1}*/,
  ],
}
export function updateGames(val: any) {
  Games = val
}

export const PAGE_SIZE_DEFAULT: { width: number; height: number } = {
  width: 1920,
  height: 1080,
}
export const WIDTH_COLUMN: number = 320
export const MAX_COUNT_COLUMN: number = 5

export let listImages: any[] = [
  { alias: 'arrow1', src: '/images/frenzy/arrow1.png' },
  { alias: 'arrow2', src: '/images/frenzy/arrow2.png' },
  { alias: 'back', src: '/images/frenzy/back.png' },
  { alias: 'bonus_back', src: '/images/frenzy/bonus_back.png' },
  { alias: 'bonus_back_info', src: '/images/frenzy/bonus_back_info.png' },
  { alias: 'bonus_btn', src: '/images/frenzy/bonus_btn.png' },
  { alias: 'bonus_close', src: '/images/frenzy/bonus_close.png' },
  { alias: 'bonus_fon', src: '/images/frenzy/bonus_fon.png' },
  { alias: 'bonus_text', src: '/images/frenzy/bonus_text.png' },
  { alias: 'bonus1', src: '/images/frenzy/bonus1.png' },
  { alias: 'bonus2', src: '/images/frenzy/bonus2.png' },
  { alias: 'down_c', src: '/images/frenzy/down_c.png' },
  { alias: 'down_l', src: '/images/frenzy/down_l.png' },
  { alias: 'down_r', src: '/images/frenzy/down_r.png' },
  { alias: 'icon1', src: '/images/frenzy/icon1.png' },
  { alias: 'icon2', src: '/images/frenzy/icon2.png' },
  { alias: 'hot_json', src: '/images/frenzy/anim/hot.json' },
  { alias: 'hot_png', src: '/images/frenzy/anim/hot.png' },
  { alias: 'new_json', src: '/images/frenzy/anim/new.json' },
  { alias: 'new_png', src: '/images/frenzy/anim/new.png' },
  { alias: 'settings', src: '/images/frenzy/settings.png' },
  { alias: 'settings2', src: '/images/frenzy/settings2.png' },
  { alias: 'top_c', src: '/images/frenzy/top_c.png' },
  { alias: 'top_l', src: '/images/frenzy/top_l.png' },
  { alias: 'top_r', src: '/images/frenzy/top_r.png' },
  { alias: 'all_png', src: '/images/frenzy/anim/all.png' },
  { alias: 'all_json', src: '/images/frenzy/anim/all.json' },
  { alias: 'bonus_png', src: '/images/frenzy/anim/bonus.png' },
  { alias: 'bonus_json', src: '/images/frenzy/anim/bonus.json' },
  { alias: 'coin_png', src: '/images/frenzy/anim/coin.png' },
  { alias: 'coin_json', src: '/images/frenzy/anim/coin.json' },
  { alias: 'fav_png', src: '/images/frenzy/anim/fav.png' },
  { alias: 'fav_json', src: '/images/frenzy/anim/fav.json' },
  { alias: 'fish_png', src: '/images/frenzy/anim/fish.png' },
  { alias: 'fish_json', src: '/images/frenzy/anim/fish.json' },
  { alias: 'logo_png', src: '/images/frenzy/anim/logo.png' },
  { alias: 'logo_json', src: '/images/frenzy/anim/logo.json' },
  { alias: 'table_png', src: '/images/frenzy/anim/table.png' },
  { alias: 'table_json', src: '/images/frenzy/anim/table.json' },
  { alias: 'user_json', src: '/images/frenzy/anim/user.json' },
  { alias: 'user_png', src: '/images/frenzy/anim/user.png' },
  // { alias: 'icon_json', src: '/images/frenzy/anim/icon.json' },
  // { alias: 'icon_png', src: '/images/frenzy/anim/icon.png' },
  { alias: 'trunc_json', src: '/images/frenzy/anim/trunc.json' },
  { alias: 'trunc_png', src: '/images/frenzy/anim/trunc.png' },
  { alias: 'news_icon', src: '/images/frenzy/news_icon.png' },
  { alias: 'news_img_1', src: '/images/frenzy/news_img_1.png' },
  { alias: 'news_img_2', src: '/images/frenzy/news_img_2.png' },
  { alias: 'updatePopup', src: '/images/frenzy/updatePopup.png' },
  { alias: 'update_btn', src: '/images/frenzy/update_btn.png' },
  { alias: 'bonus_bg', src: '/images/frenzy/bonus/bonus_bg.png' },
  { alias: 'popup_title_daily', src: '/images/frenzy/bonus/popup_title_daily.png' },
  { alias: 'popup_title_weekly', src: '/images/frenzy/bonus/popup_title_weekly.png' },
  { alias: 'empty_bonus_star', src: '/images/frenzy/bonus/empty_bonus_star.png' },
  { alias: 'filled_bonus_star', src: '/images/frenzy/bonus/filled_bonus_star.png' },
  { alias: 'help', src: '/images/frenzy/bonus/help.png' },
  // { alias: 'bonus_close_bonus', src: '/images/frenzy/bonus/bonus_close.png' },
  { alias: 'daily_tab_active', src: '/images/frenzy/bonus/daily_tab_active.png' },
  { alias: 'to_daily_tab', src: '/images/frenzy/bonus/to_daily_tab.png' },
  { alias: 'weekly_tab_active', src: '/images/frenzy/bonus/weekly_tab_active.png' },
  { alias: 'to_weekly_tab', src: '/images/frenzy/bonus/to_weekly_tab.png' },
  { alias: 'total_coin_bg', src: '/images/frenzy/bonus/total_coin_bg.png' },
  { alias: 'remaining_time_bg', src: '/images/frenzy/bonus/remaining_time_bg.png' },
  { alias: '0', src: '/images/frenzy/bonus/0.png' },
  { alias: '1', src: '/images/frenzy/bonus/1.png' },
  { alias: '2', src: '/images/frenzy/bonus/2.png' },
  { alias: '3', src: '/images/frenzy/bonus/3.png' },
  { alias: '4', src: '/images/frenzy/bonus/4.png' },
  { alias: '5', src: '/images/frenzy/bonus/5.png' },
  { alias: 'btn_completed', src: '/images/frenzy/bonus/btn_completed.png' },
  { alias: 'btn_inprogress', src: '/images/frenzy/bonus/btn_inprogress.png' },
  { alias: 'daily_progress_bar', src: '/images/frenzy/bonus/daily_progress_bar.png' },
  { alias: 'weekly_progress_bar', src: '/images/frenzy/bonus/weekly_progress_bar.png' },
]
